apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nautobot.name" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nautobot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: "{{ include "nautobot.fullname" . }}"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nautobot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nautobot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: nautobot
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.nautobot.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.nautobot.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-secret
                  key: nautobot-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/nautobot/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
