---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nautobot.fullnameOverride }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nautobot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: "{{ include "nautobot.fullname" . }}"
  replicas: {{ .Values.nautobot.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nautobot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nautobot
          image: "{{ .Values.nautobot.image.repository }}:{{ .Values.nautobot.image.tag }}"
          imagePullPolicy: {{ .Values.nautobot.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: nautobot
          env:
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.nautobot.superUser.create | quote }}
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: superuser
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.nautobot.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_NAME
              value: {{ .Values.nautobot.superUser.name }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superuser
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.nautobot.database.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
