---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nautobot.fullnameOverride }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nautobot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: "{{ include "nautobot.fullname" . }}"
  replicas: {{ .Values.nautobot.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nautobot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nautobot
          image: "{{ .Values.nautobot.image.repository }}:{{ .Values.nautobot.image.tag }}"
          imagePullPolicy: {{ .Values.nautobot.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: nautobot
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.nautobot.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.nautobot.config.caches_backend }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.nautobot.superUser.create | quote }}
            - name: NAUTOBOT_REDIS_HOST
              value: redis.redis.svc.cluster.local
            - name: NAUTOBOT_REDIS_SCHEME
              value: redis
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: superuser
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.nautobot.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_NAME
              value: {{ .Values.nautobot.superUser.name }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superuser
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.nautobot.database.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          volumeMounts:
            - name: config
              mountPath: /opt/nautobot/
            - name: git
              mountPath: /opt/nautobot/
              read_only: false
      volumes:
        - name: config
          configMap:
            name: nautobot-config
            items:
              - key: nautobot_config.py
                path: nautobot_config.py
        - name: git
          persistentVolumeClaim:
            claimName: git
