apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  nautobot_config.py: |-
    {{- $.Files.Get "config/nautobot_config.py" | nindent 4 }}

  .bashrc: |-
    {{- $.Files.Get "config/nb.bashrc" | nindent 4 }}

  uwsgi.ini: |-
    {{- $.Files.Get "config/uwsgi.ini" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.celery.name }}
data:
  nautobot_config.py: |-
    {{- $.Files.Get "config/nautobot_config.py" | nindent 4 }}

  .bashrc: |-
    {{- $.Files.Get "config/nb.bashrc" | nindent 4 }}
