apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
    nautobot_config.py: |
{{ range .Files.Lines "nautobot_config.py" }}{{ . | nindent 6 }}{{ end }}
    .bashrc: |-
      #!/bin/bash

      NAUTOBOT_ROOT=/opt/nautobot
      PATH="/opt/nautobot/bin:$PATH"

      export NAUTOBOT_ROOT
      export PATH
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-config
data:
  nautobot_config.py: |
{{ range .Files.Lines "nautobot_config.py" }}{{ . | nindent 6 }}{{ end }}
  .bashrc: |-
    #!/bin/bash

    PATH="/opt/nautobot/bin:$PATH"

    export PATH
