apiVersion: v1
kind: ConfigMap
metadata:
  name: nautobot-config
  labels:
    app.kubernetes.io/name: nautobot
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .bashrc: |-
    {{- $.Files.Get "config/nautobot.bashrc" | nindent 4 }}

  uwsgi.ini: |-
    {{- $.Files.Get "config/uwsgi.ini" | nindent 4 }}

  resolv.conf: |-
    {{- $.Files.Get "config/resolv.conf" | nindent 4 }}

  reqs: |-
    {{- $.Files.Get "config/reqs" | nindent 4 }}

  init.sh: |-
    {{- $.Files.Get "config/nautobot.init.sh" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nautobot-celery-config
  labels:
    app.kubernetes.io/name: nautobot-celery-config
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .bashrc: |-
    {{- $.Files.Get "config/celery.bashrc" | nindent 4 }}

  reqs: |-
    {{- $.Files.Get "config/reqs" | nindent 4 }}

  resolv.conf: |-
    {{- $.Files.Get "config/resolv.conf" | nindent 4 }}

  init.sh: |-
    {{- $.Files.Get "config/celery.init.sh" | nindent 4 }}
