---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautobot-celery
  labels:
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: ghcr
      containers:
        - name: nautobot-celery
          command:
          - /bin/sh
          - >-
            -c
          - >-
            while true; do sleep 3600; done
          # command:
          #   - /opt/celery/bin/nautobot-server
          #   - celery
          #   - start
          image: ghcr.io/edwardtheharris/helm-nautobot/celery:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: stat
              containerPort: 1024
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          volumeMounts:
            - name: nautobot-celery-config
              mountPath: /opt/.celery
            - name: nautobot-celery
              mountPath: /opt/celery/
              subPath: celery
      volumes:
        - name: nautobot-celery-config
          configMap:
            name: nautobot-celery-config
        - name: nautobot-celery
          persistentVolumeClaim:
            claimName: celery
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      serviceAccountName: nautobot
      serviceAccount: nautobot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautobot-celery-beat
  labels:
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: nautobot-celery-beat
          command:
          - /bin/sh
          - >-
            -c
          - >-
            while true; do sleep 3600; done
            # - /opt/celery/bin/nautobot-server
            # - celery
            # - beat
          image: ghcr.io/edwardtheharris/helm-nautobot/celery:0.0.3
          volumeMounts:
            - name: nautobot-celery-beat
              mountPath: /opt/celery/
              subPath: celery
            - name: nautobot-celery-config
              mountPath: /opt/.celery
      volumes:
        - name: nautobot-celery-config
          configMap:
            name: nautobot-celery-config
        - name: nautobot-celery-beat
          persistentVolumeClaim:
            claimName: celery-beat
