{{- if eq .Values.type "Deployment" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ .Release.Name }}
    volume.kubernetes.io/name: {{ .Release.Name }}
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    pvc.kubernetes.io/instance: {{ .Release.Name }}
    pvc.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}-opt
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-linear
  volumeMode: Filesystem
{{ end }}
{{ if .Values.persistence.claim.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ .Release.Name }}-striped
    app.kubernetes.io/name: {{ .Release.Name }}-striped
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
    pvc.kubernetes.io/name: {{ .Release.Name }}-striped
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    pvc.kubernetes.io/instance: {{ .Release.Name }}-striped
    pvc.kubernetes.io/name: {{ .Release.Name }}-striped
  name: {{ .Release.Name }}-striped
  namespace: nautobot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-striped
  volumeMode: Filesystem
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ .Release.Name }}
    volume.kubernetes.io/name: celery-beat-pvc
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: filesystem
    pvc.kubernetes.io/instance: {{ .Release.Name }}
    pvc.kubernetes.io/name: celery-beat-pvc
  name: celery-beat-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-linear
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ .Release.Name }}
    volume.kubernetes.io/name: celery-worker-pvc
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: filesystem
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-worker-pvc
  name: celery-worker-pvc
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-linear
  volumeMode: Filesystem
