{{ if .Values.persistence.claim.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ .Release.Name }}-striped
    app.kubernetes.io/name: {{ .Release.Name }}-striped
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
    pvc.kubernetes.io/name: {{ .Release.Name }}-striped
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    pvc.kubernetes.io/instance: {{ .Release.Name }}-striped
    pvc.kubernetes.io/name: {{ .Release.Name }}-striped
  name: {{ .Release.Name }}-striped
  namespace: nautobot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-striped
  volumeMode: Filesystem
{{ end }}
