{{- if eq .Values.type "Deployment" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ include "nautobot.pvc" . }}
    {{- include "nautobot.labels" . | nindent 4 }}
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    {{- include "nautobot.labels" . | nindent 4 }}
    name: {{ include "nautobot.pvc" . }}
  name: {{ include "nautobot.pvc" . | quote }}
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-linear
  volumeMode: Filesystem
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: celery-beat
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-beat
    app.kubernetes.io/part-of: {{ .Release.Name }}
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-beat
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: celery-beat
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-linear
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: celery-worker
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-worker
    app.kubernetes.io/part-of: {{ .Release.Name }}
    volume.kubernetes.io/storage-provisioner: lvm.csi.metal-stack.io
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-worker
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: celery-worker
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-lvm-linear
  volumeMode: Filesystem
