---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery
spec:
  storageClassName: csi-lvm-linear
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-beat
spec:
  storageClassName: csi-lvm-linear
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
