---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.{{ .Values.database.name }}
  namespace: nautobot
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
  username: {{ .Values.database.username | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.nameOverride }}
  name: {{ .Values.superUser.secret.name }}
  namespace: nautobot
type: Opaque
data:
  email: {{ .Values.superUser.email | b64enc | quote }}
  password: {{ .Values.superUser.password | b64enc }}
  secretKey: {{ .Values.superUser.secretKey | b64enc }}
  token: {{ .Values.superUser.token | b64enc }}
  username: {{ .Values.superUser.username | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.github.ghcr
  namespace: nautobot
data:
    .dockerconfigjson: {{ .Values.image.secret.data }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.github.sso
  namespace: nautobot
type: Opaque
data:
  social_auth_github_key: {{ .Values.sso.social_auth_github_key | b64enc }}
  social_auth_github_secret: {{ .Values.sso.social_auth_github_secret | b64enc }}
