---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kubernetes.io/name: secret.{{ .Values.database.name }}
  labels:
    secret.kubernetes.io/name: secret.{{ .Values.database.name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.{{ .Values.database.name }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
  username: {{ .Values.database.username | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kubernetes.io/name: {{ .Values.superUser.secret.name }}
  labels:
    secret.kubernetes.io/name: {{ .Values.superUser.secret.name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.superUser.secret.name }}
type: Opaque
data:
  password: {{ .Values.superUser.password | b64enc }}
  token: {{ .Values.superUser.token | b64enc }}
  username: {{ .Values.superUser.username | b64enc }}
