---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kubernetes.io/name: secret.{{ .Values.database.name }}
  labels:
    secret.kubernetes.io/name: secret.{{ .Values.database.name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.{{ .Values.database.name }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
  username: {{ .Values.database.username | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    secret.kubernetes.io/name: {{ .Values.superUser.secret.name }}
  labels:
    secret.kubernetes.io/name: {{ .Values.superUser.secret.name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.superUser.secret.name }}
type: Opaque
data:
  password: {{ .Values.superUser.password | b64enc }}
  token: {{ .Values.superUser.token | b64enc }}
  username: {{ .Values.superUser.username | b64enc }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.image.secret.data }}
kind: Secret
metadata:
  annotations:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    secret.kubernetes.io/instance: nautobot
    secret.kubernetes.io/name: ghcr
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    secret.kubernetes.io/name: ghcr
  name: ghcr
  namespace: nautobot
data:
    .dockerconfigjson: {{ .Values.image.secret.data }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kubernetes.io/name: secret.github.sso
  labels:
    secret.kubernetes.io/name: secret.github.sso
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.github.sso
type: Opaque
data:
  social_auth_github_key: {{ .Values.nautobot.social_auth_github_key | b64enc }}
  social_auth_github_secret: {{ .Values.nautobot.social_auth_github_secret | b64enc }}
