---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kubernetes.io/name: secret.{{ .Values.database.name }}
  labels:
    secret.kubernetes.io/name: secret.{{ .Values.database.name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.{{ .Values.database.name }}
type: Opaque
data:
    {{ .Files.Get "{{ .Values.database.secretfile }}" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secret.kubernetes.io/name: secret.{{ .Values.superUser.name }}
  labels:
    secret.kubernetes.io/name: secret.{{ .Values.superUser.name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: secret.{{ .Values.superUser.name }}
type: Opaque
data:
    {{ .Files.Get "{{ .Values.superUser.secretfile }}" | b64enc }}
