{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    service.kubernetes.io/name: {{ .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: nautobot
  selector:
    {{ .Values.service.selectorLabels | toYaml | nindent 4 }}
{{ end }}
