apiVersion: v1
kind: Service
metadata:
  name: {{ include "nautobot.fullname" . }}
  labels:
    {{- include "nautobot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nautobot.service.type }}
  ports:
    - port: {{ .Values.nautobot.service.port }}
      targetPort: 5432
      protocol: TCP
      name: nautobot
  selector:
    {{- include "nautobot.selectorLabels" . | nindent 4 }}
