{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: nautobot
    app.kubernetes.io/part-of: nautobot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: nautobot
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: nautobot
---
apiVersion: v1
kind: Service
metadata:
  name: celery-beat
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-beat
    app.kubernetes.io/part-of: nautobot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: celery-beat
  selector:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-beat
---
apiVersion: v1
kind: Service
metadata:
  name: celery-worker
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-worker
    app.kubernetes.io/part-of: nautobot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5673
      targetPort: 5673
      protocol: TCP
      name: celery-worker
  selector:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: celery-worker
{{ end }}
